"""fixed column

Revision ID: 0d64e2179c45
Revises: 3876eb0836c6
Create Date: 2023-04-03 11:24:05.524848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d64e2179c45'
down_revision = '3876eb0836c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_column('usernamename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usernamename', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
